# Generated by Django 3.0.3 on 2020-03-03 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Код урока')),
                ('name', models.CharField(max_length=50, verbose_name='Название урока')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=15, verbose_name='ID студента')),
                ('firstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('course', models.ManyToManyField(related_name='course_student', to='attendance.Course', verbose_name='Курсы')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance', verbose_name='посещаемость')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples', models.ImageField(upload_to='fingerprints/', verbose_name='Отпечаток')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_course', to='attendance.Teacher', verbose_name='Инструктор'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Course', verbose_name='названия урока'),
        ),
    ]
